galaxy_info:
  author: Homero Pawlowski
  description: Template an entire directory structure efficiently
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - oasis

dependencies: []
