- name: converge
  gather_facts: false
  hosts: all
  vars:
    base: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/../shared/"
  roles:
    - role: templates
      osp_templates_input_dir: "{{ base }}/in/"
      osp_templates_output_dir: /out
      value: "my string"
