driver:
  name: openstack
platforms:
  - name: test-osp_director
    flavor: ci.m1.xlarge
    nics:
      - net-name: provider_net_cci_4
      - net-name: provider_net_cci_9
provisioner:
  inventory:
    host_vars:
      test-osp_director:
        undercloud:
          hostname: director.example.com
          nameservers:
            - "10.11.142.1"
            - "10.11.5.19"
          ntp_server: "0.rhel.pool.ntp.org"
          install_ceph_ansible: false
