- name: list files described as changed by git
  shell: |
    set -o pipefail -e
    cd {{ osp_templates_input_dir }}; git status -- short . | \
    grep -v '^\\sD' | awk '{print $2}'
  register: _shell_output
  changed_when: false

- debug:
    var: _shell_output.stdout_lines

- name: template {{ item }} to {{ osp_templates_output_dir }}/{{ item }}
  template:
    src: "{{ osp_templates_input_dir }}/{{ item }}"
    dest: "{{ osp_templates_output_dir }}/{{ item }}"
    variable_start_string: "{{ osp_templates_variable_start_string }}"
    variable_end_string: "{{ osp_templates_variable_end_string }}"
    owner: "{{ osp_templates_owner | omit }}"
  loop: "{{ _shell_output.stdout_lines }}"
  register: _template_output
