- name: list files described as changed by git
  shell: |
    set -o pipefail -e
    git status --short . | grep -v '^\\sD' | awk '{print $2}'
  args:
    chdir: "{{ osp_templates_input_dir }}"
    executable: /bin/bash
  register: _shell_output
  changed_when: false
  delegate_to: localhost

- debug:
    var: _shell_output.stdout_lines

- name: template {{ item }} to {{ osp_templates_output_dir }}/{{ item }}
  template:
    src: "{{ osp_templates_input_dir }}/{{ item }}"
    dest: "{{ osp_templates_output_dir }}/{{ item }}"
    variable_start_string: "{{ osp_templates_variable_start_string }}"
    variable_end_string: "{{ osp_templates_variable_end_string }}"
    owner: "{{ osp_templates_owner | default(omit) }}"
    mode: 0644
  loop: "{{ _shell_output.stdout_lines }}"
  register: _template_output
