driver:
  name: docker
platforms:
  - name: osp_templates_sample_dir
    image: centos:7
provisioner:
  playbooks:
    prepare: ../shared/prepare.yml
    cleanup: ../shared/cleanup.yml
  inventory:
    group_vars:
      osp_templates_quick_mode: true
