driver:
  name: docker
platforms:
  - name: osp_templates_quick_mode
    image: centos:7
provisioner:
  playbooks:
    converge: playbook.yml
  inventory:
    group_vars:
      osp_templates_quick_mode: true
